### ISSUE TITLE
debian suspend  leads to starting Ollama without Cuda

### ISSUE THREAD

**Issue by Dinobali** [varunvasudeva1/ollama-server-docs#1]
hi,

I did all as described and everything works fine. the only issue I have is that debian graphical has a suspension mode after a while of inactivity. this leads to restarting or starting Ollama without gpu. it then uses cpu or I have to reboot system completely to get it work with gpu again. I will set suspend to never for now but I need it to suspend and when I start it again it should work using gpu. this would be nice if you have a solution. thank you

**Comment by varunvasudeva1** [comment]
Hey @Dinobali! You have an unfortunate problem, because my research on this topic so far shows that peoiple who've had this issue have likely not solved it (or not posted updates, at the very least). Suspend seems to be a pain point with Linux.

Examples:
https://unix.stackexchange.com/questions/346010/nvidia-driver-unloads-after-a-system-suspend
https://superuser.com/questions/1703434/suspend-and-nvidia-problems-in-fresh-debian-stable-install

I don't know the specs of your system so here's what I could think of:
If you have a CPU with integrated graphics (and assuming you're using an Nvidia GPU), it could be that Nvidia's Optimus is kicking in when your server hits a suspended state to optimize the usage of the server's resources.

Potential solutions:

1) You could tell your system to only use the Nvidia GPU by following the steps [here](https://wiki.debian.org/NVIDIA%20Optimus#Using_only_one_GPU). This process may be a little painstaking (the guide itself mentions trial and error being the only way out) but it seems worth it to gain stability of runtime. I'd also advise just going through that whole page in case something else on there sounds like it might work.

2) Just like you scheduled `init.bash` to run on reboot, you could use the crontab to schedule a restart for Ollama on termination of suspension. To restart Ollama, you'd use `systemctl restart ollama`. I'm not 100% sure this would work - it could be that, because your system doesn't register the GPU at all, Ollama can't find it either and still defaults to the CPU when restarting. On the other hand, Ollama's restart could prompt the system to find and load the GPU.

3) You could disable sleep/suspend completely and use the shutdown schedule + wake-on-LAN method. For example, you tell the machine (via `init.bash`) to shutdown at 2am everyday and, the next day, send the appropriate signal to the machine to wake it when you need it. If you use an SSD and don't have a lot of HDDs in your machine (spinning up and down isn't good for them in the long term), this solution isn't all that bad and shouldn't hinder your workflow too badly, while also conserving power when not needed. Check out [this guide](https://wiki.debian.org/WakeOnLan) to enable Wake On LAN.

> [!TIP]
> If you have an iPhone, turning the server on/off outside of a crontab schedule is easy with Apple Shortcuts. Create separate shortcuts to turn the server on (WOL command) and off (`sudo shutdown`) and trigger as needed. It's possible to automate this using Shortcut automations even, but I haven't personally done this.

In order, I'd try 2 -> 1 -> 3. Run `systemctl restart ollama` when your system's newly woken up from suspension and see if it loads the GPU. If it does, this is probably the easiest solution when you don't need to tweak anything more than the crontab - schedule that command to run on wake and you're set. If it doesn't, you'll want a more permanent solution like 1 in any case. If 1 doesn't work either, you may just have to cop out and go with 3. Please let me know where your testing goes!

**Comment by Dinobali** [comment]
thank you for this. I now just made my pc a server 24 on. I also made some beautiful local stuff using langchain, ollama and openai for chatting with local files and getting accurate answers from the provided books. I will try to share this soon.

**Comment by varunvasudeva1** [comment]
My pleasure. Sounds good - RAG is a burgeoning area with a lot of work to be done. Closing this for now!
